version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: ula-aca-development-nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - aca-py
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - aca-py
    environment:
      NGINX_PROXY_CONTAINER: ula-aca-development-nginx-proxy
      DEFAULT_EMAIL: timo@animo.id
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam

  faber-register-seed:
    image: byrnedo/alpine-curl
    command: >-
      http://test.bcovrin.vonx.io/register
      -X POST
      -d '{"alias":"Faber Agent","seed":"faber_seed_000000000000000000001","role":"TRUST_ANCHOR"}'

  alice-register-seed:
    image: byrnedo/alpine-curl
    command: >-
      http://test.bcovrin.vonx.io/register
      -X POST
      -d '{"alias":"Alice Agent","seed":"alice_seed_000000000000000000001","role":"TRUST_ANCHOR"}'

  acme-register-seed:
    image: byrnedo/alpine-curl
    command: >-
      http://test.bcovrin.vonx.io/register
      -X POST
      -d '{"alias":"Acme Agent","seed":"acme_seed_0000000000000000000001","role":"TRUST_ANCHOR"}'

  faber-aca-py:
    image: bcgovimages/aries-cloudagent:py36-1.15-0_0.5.6
    environment:
      VIRTUAL_HOST: aca.faber.demo.animo.id
      LETSENCRYPT_HOST: aca.faber.demo.animo.id
      VIRTUAL_PORT: "7002"
    depends_on:
      - faber-webhook-relay
      - faber-register-seed
    networks:
      - aca-py
    ports:
      - "7002"
      - "7000:7000"
      - "7001:7001"
    command: >-
      start
        --label "Faber Agent"
        --endpoint http://aca.faber.demo.animo.id:7000
        --genesis-url http://test.bcovrin.vonx.io/genesis
        --webhook-url http://faber-webhook-relay:8080
        --admin 0.0.0.0 7002 
        --admin-insecure-mode 
        --inbound-transport http 0.0.0.0 7000
        --inbound-transport ws 0.0.0.0 7001 
        --outbound-transport http 
        --outbound-transport ws
        --wallet-type indy
        --wallet-name "Faber Wallet"
        --wallet-key FaberWallet000000
        --seed faber_seed_000000000000000000001
        --log-level DEBUG
        --debug-connections
        --auto-accept-invites
        --auto-accept-requests
        --auto-respond-messages
        --auto-respond-credential-proposal
        --auto-respond-credential-offer
        --auto-respond-credential-request
        --auto-respond-presentation-proposal
        --auto-respond-presentation-request
        --auto-store-credential
        --auto-verify-presentation

  alice-aca-py:
    image: bcgovimages/aries-cloudagent:py36-1.15-0_0.5.6
    environment:
      VIRTUAL_HOST: aca.alice.demo.animo.id
      LETSENCRYPT_HOST: aca.alice.demo.animo.id
      VIRTUAL_PORT: "8002"
    depends_on:
      - alice-webhook-relay
      - alice-register-seed
    networks:
      - aca-py
    ports:
      - "8002"
      - "8000:8000"
      - "8001:8001"
    command: >-
      start 
        --endpoint http://aca.alice.demo.animo.id:8000
        --admin 0.0.0.0 8002    
        --admin-insecure-mode
        --webhook-url http://alice-webhook-relay:8080
        --label "Alice Agent"
        --inbound-transport http 0.0.0.0 8000 
        --inbound-transport ws 0.0.0.0 8001 
        --outbound-transport http 
        --outbound-transport ws 
        --genesis-url http://test.bcovrin.vonx.io/genesis
        --wallet-type indy
        --wallet-name "Alice Wallet"
        --wallet-key AliceWallet000000
        --seed alice_seed_000000000000000000001
        --log-level DEBUG
        --debug-connections
        --auto-accept-invites
        --auto-accept-requests
        --auto-respond-messages
        --auto-respond-credential-proposal
        --auto-respond-credential-offer
        --auto-respond-credential-request
        --auto-respond-presentation-proposal
        --auto-respond-presentation-request
        --auto-store-credential
        --auto-verify-presentation

  acme-aca-py:
    image: bcgovimages/aries-cloudagent:py36-1.15-0_0.5.6
    environment:
      VIRTUAL_HOST: aca.acme.demo.animo.id
      LETSENCRYPT_HOST: aca.acme.demo.animo.id
      VIRTUAL_PORT: "6002"
    depends_on:
      - acme-webhook-relay
      - acme-register-seed
    networks:
      - aca-py
    ports:
      - "6002"
      - "6000:6000"
      - "6001:6001"
    command: >-
      start 
        --endpoint http://aca.acme.demo.animo.id:6000
        --admin 0.0.0.0 6002    
        --admin-insecure-mode
        --webhook-url http://acme-webhook-relay:8080
        --label "Acme Agent"
        --inbound-transport http 0.0.0.0 6000 
        --inbound-transport ws 0.0.0.0 6001 
        --outbound-transport http 
        --outbound-transport ws 
        --genesis-url http://test.bcovrin.vonx.io/genesis
        --wallet-type indy
        --wallet-name "Acme Wallet"
        --wallet-key AcmeWallet0000000
        --seed acme_seed_0000000000000000000001
        --log-level DEBUG
        --debug-connections
        --auto-accept-invites
        --auto-accept-requests
        --auto-respond-messages
        --auto-respond-credential-proposal
        --auto-respond-credential-offer
        --auto-respond-credential-request
        --auto-respond-presentation-proposal
        --auto-respond-presentation-request
        --auto-store-credential
        --auto-verify-presentation

  faber-webhook-relay:
    image: karimstekelenburg/aries-cloudagent-webhook-relay
    environment:
      VIRTUAL_HOST: whr.faber.demo.animo.id
      LETSENCRYPT_HOST: whr.faber.demo.animo.id
      VIRTUAL_PORT: "8080"
    networks:
      - aca-py
    command: --log DEBUG --api-key 1e08eef8-1808-414c-b685-edce8b034ee4

  alice-webhook-relay:
    image: karimstekelenburg/aries-cloudagent-webhook-relay
    environment:
      VIRTUAL_HOST: whr.alice.demo.animo.id
      LETSENCRYPT_HOST: whr.alice.demo.animo.id
      VIRTUAL_PORT: "8080"
    networks:
      - aca-py
    command: --log DEBUG --api-key 979ee50b-9021-4cce-8f99-1c184e778347

  acme-webhook-relay:
    image: karimstekelenburg/aries-cloudagent-webhook-relay
    environment:
      VIRTUAL_HOST: whr.acme.demo.animo.id
      LETSENCRYPT_HOST: whr.acme.demo.animo.id
      VIRTUAL_PORT: "8080"
    networks:
      - aca-py
    command: --log DEBUG --api-key 62517f51-a238-427a-9912-6c632ef12fe4

  acme-faber-demo:
    image: nginx:1.19.6-alpine
    volumes:
      - ./demo:/var/www:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - aca-py
    environment:
      VIRTUAL_HOST: demo.animo.id
      LETSENCRYPT_HOST: demo.animo.id
      VIRTUAL_PORT: "80"

networks:
  aca-py:
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
