version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: ula-aca-development-nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - aca-py
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - aca-py
    environment:
      NGINX_PROXY_CONTAINER: ula-aca-development-nginx-proxy
      DEFAULT_EMAIL: timo@glastra.me
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam

  faber-register-seed:
    image: byrnedo/alpine-curl
    networks:
      - von
    command: >-
      http://von_webserver_1:8000/register
      -X POST
      -d '{"alias":"Faber Agent","seed":"faber_seed_000000000000000000001","role":"TRUST_ANCHOR"}'

  alice-register-seed:
    image: byrnedo/alpine-curl
    networks:
      - von
    command: >-
      http://von_webserver_1:8000/register
      -X POST
      -d '{"alias":"Alice Agent","seed":"alice_seed_000000000000000000001","role":"TRUST_ANCHOR"}'

  acme-register-seed:
    image: byrnedo/alpine-curl
    networks:
      - von
    command: >-
      http://von_webserver_1:8000/register
      -X POST
      -d '{"alias":"Acme Agent","seed":"acme_seed_0000000000000000000001","role":"TRUST_ANCHOR"}'

  faber-aca-py:
    image: bcgovimages/aries-cloudagent:py36-1.11-1_0.4.0
    ports:
      - 7002:7002
      - 7000:7000
      - 7001:7001
    environment:
      VIRTUAL_HOST: faber.glastra.dev
      LETSENCRYPT_HOST: faber.glastra.dev
      VIRTUAL_PORT: "7002"
    depends_on:
      - faber-webhook-relay
      - faber-register-seed
    networks:
      - von
      - aca-py
    command: >-
      start
        --label "Faber Agent"
        --endpoint http://faber-aca-py:7000
        --genesis-url http://von_webserver_1:8000/genesis
        --webhook-url http://faber-webhook-relay:8080
        --admin 0.0.0.0 7002 
        --admin-insecure-mode 
        --inbound-transport http 0.0.0.0 7000
        --inbound-transport ws 0.0.0.0 7001 
        --outbound-transport http 
        --outbound-transport ws
        --wallet-type indy
        --wallet-name "Faber Wallet"
        --wallet-key FaberWallet000000
        --seed faber_seed_000000000000000000001

  alice-aca-py:
    image: bcgovimages/aries-cloudagent:py36-1.11-1_0.4.0
    ports:
      - 8002:8002
      - 8000:8000
      - 8001:8001
    environment:
      VIRTUAL_HOST: alice.glastra.dev
      LETSENCRYPT_HOST: alice.glastra.dev
      VIRTUAL_PORT: "8002"
    depends_on:
      - alice-webhook-relay
      - alice-register-seed
    networks:
      - von
      - aca-py
    command: >-
      start 
        --endpoint http://alice-aca-py:8000 
        --admin 0.0.0.0 8002    
        --admin-insecure-mode
        --webhook-url http://alice-webhook-relay:8080
        --label "Alice Agent"
        --inbound-transport http 0.0.0.0 8000 
        --inbound-transport ws 0.0.0.0 8001 
        --outbound-transport http 
        --outbound-transport ws 
        --genesis-url http://von_webserver_1:8000/genesis
        --wallet-type indy
        --wallet-name "Alice Wallet"
        --wallet-key AliceWallet000000
        --seed alice_seed_000000000000000000001

  acme-aca-py:
    image: bcgovimages/aries-cloudagent:py36-1.11-1_0.4.0
    ports:
      - 6002:6002
      - 6000:6000
      - 6001:6001
    environment:
      VIRTUAL_HOST: acme.glastra.dev
      LETSENCRYPT_HOST: acme.glastra.dev
      VIRTUAL_PORT: "6002"
    depends_on:
      - acme-webhook-relay
      - acme-register-seed
    networks:
      - von
      - aca-py
    command: >-
      start 
        --endpoint http://acme-aca-py:6000 
        --admin 0.0.0.0 6002    
        --admin-insecure-mode
        --webhook-url http://acme-webhook-relay:8080
        --label "Acme Agent"
        --inbound-transport http 0.0.0.0 6000 
        --inbound-transport ws 0.0.0.0 6001 
        --outbound-transport http 
        --outbound-transport ws 
        --genesis-url http://von_webserver_1:8000/genesis
        --wallet-type indy
        --wallet-name "Acme Wallet"
        --wallet-key AcmeWallet0000000
        --seed acme_seed_0000000000000000000001

  faber-webhook-relay:
    image: docker.pkg.github.com/ula-aca/aries-cloudagent-webhook-relay/aca-whr:latest
    environment:
      VIRTUAL_HOST: whr.faber.glastra.dev
      LETSENCRYPT_HOST: whr.faber.glastra.dev
      VIRTUAL_PORT: "8080"
    networks:
      - aca-py
    ports:
      - 7080:8080
    command: --log DEBUG

  alice-webhook-relay:
    image: docker.pkg.github.com/ula-aca/aries-cloudagent-webhook-relay/aca-whr:latest
    environment:
      VIRTUAL_HOST: whr.alice.glastra.dev
      LETSENCRYPT_HOST: whr.alice.glastra.dev
      VIRTUAL_PORT: "8080"
    networks:
      - aca-py
    ports:
      - 8080:8080
    command: --log DEBUG

  acme-webhook-relay:
    image: docker.pkg.github.com/ula-aca/aries-cloudagent-webhook-relay/aca-whr:latest
    environment:
      VIRTUAL_HOST: whr.acme.glastra.dev
      LETSENCRYPT_HOST: whr.acme.glastra.dev
      VIRTUAL_PORT: "8080"
    networks:
      - aca-py
    ports:
      - 6080:8080
    command: --log DEBUG

networks:
  von:
    external:
      name: von_von
  aca-py:
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
