name: Continuous Integration

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    # TODO: Make this deploy nicer
    steps:
      - name: Start development setup on remote ssh server with docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~
            rm -rf ./aries-cloudagent-ula-development-setup
            echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
            git clone --recursive https://github.com/ula-aca/aries-cloudagent-ula-development-setup
            cd aries-cloudagent-ula-development-setup 
            docker-compose up -d --force-recreate
