name: remote ssh command
on: [push]
jobs:

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf ./aries-cloudagent-ula-development-setup
          docker login docker.pkg.github.com -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          git clone --recursive https://github.com/utrecht-innovation/aries-cloudagent-ula-development-setup
          cd aries-cloudagent-ula-development-setup 
          # ./von-network/manage build
          # ./von-network/manage up &
          # disown
          # sleep 60
          docker-compose up &
          disown